---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom
  labels:
    app: custom
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
        - name: web
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.image.httpport }} 
              protocol: TCP
            - containerPort: 8443
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
        - name: db
          image: registry.access.redhat.com/rhscl/mysql-80-rhel7
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: cm-redhat
                  key: user
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: cm-redhat
                  key: database
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-redhat
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-redhat
                  key: root_password
          ports:
            - containerPort: 3306
              protocol: TCP
