---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: custom
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: custom
  type: {{ .Values.service.type }}
