replicaCount: 4

image:
  repository: registry.access.redhat.com/ubi9/httpd-24
  pullPolicy: IfNotPresent
  tag: latest
  httpport: 8080

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 10m
    memory: 100Mi
  requests:
    cpu: 5m
    memory: 25Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# livenessProbe:
#   httpGet:
#     path: /
#     port: http
# readinessProbe:
#   httpGet:
#     path: /
#     port: http
# 
# #This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80
# 
# # Additional volumes on the output Deployment definition.
# volumes: []
# # - name: foo
# #   secret:
# #     secretName: mysecret
# #     optional: false
# 
# # Additional volumeMounts on the output Deployment definition.
# volumeMounts: []
# # - name: foo
# #   mountPath: "/etc/foo"
# #   readOnly: true
# 
# nodeSelector: {}
# 
# tolerations: []
# 
# affinity: {}
