apiVersion: v1
kind: Pod
metadata:
  name: danielpod
  labels:
    app: complex
spec:
  restartPolicy: OnFailure
  containers:
    - name: web
      image: registry.access.redhat.com/ubi9/httpd-24
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
    - name: db
      image: registry.access.redhat.com/rhscl/mysql-80-rhel7
      env:
        - name: MYSQL_USER
          value: rasmus
        - name: MYSQL_PASSWORD
          value: mypa55
        - name: MYSQL_DATABASE
          value: items
        - name: MYSQL_ROOT_PASSWORD
          value: r00tpa55
      ports:
        - containerPort: 3306
          protocol: TCP
