apiVersion: v1
kind: Pod
metadata:
  name: hanspod
  labels:
    you: me
    rasmus: akhil
  # namespace: test
spec:
  containers:
    - name: web
      image: registry.access.redhat.com/ubi9/httpd-24
      # image: registry.access.redhat.com/ubi9/httpd-24
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
# status:
#
