apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: example
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "example",
      "type": "host-device",
      "device": "ens4",
      "ipam": {
        "type": "dhcp"
      }
    }
